[[edge_functions]]
  path = "/*"
  function = "handler"

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = "public,max-age=31536000,immutable"
    access-control-allow-origin = "*"

[build]
environment = {NODE_VERSION = '16'}
command = 'yarn build'
publish = 'dist/client'

[dev]
autoLaunch = false